# VitrnX sample TOML config file.

# No prefix
test = "a value from config"

[auth]
adminEmail = "admin@example.com"
anonymousEmail = "guest@example.com"
knownRoles = ["ADMIN/Administrator",  
	"USER_ADMIN/User Admin",
	"MODERATOR/Moderator",	
	"EDITOR/Editor",
	"VOLUNTEER/Volunteer",
	"GUEST/Guest",
	"REGISTERED/Registered",
	"ANONYMOUS/Anonymous"]

[users]
